version: '3'
services:
  password_generator-server:
    image: "marckruszynski/password_generator-server"
    environment:
      - GMAIL_PASSWORD=password
  password_generator-frontend:
    image: "marckruszynski/password_generator-frontend"
    ports:
      - "4200:4200"
    links:
      - "password_generator-server:server"
  nginx:
    image: "nginx"
    depends_on:
      - password_generator-server
      - password_generator-frontend
    links:
      - "password_generator-server:server"
    volumes:
      - shared:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
volumes:
  shared: {}
